# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tFEtGY1D_UzLV0ECv41okgxvG2-u-Ru_

1.Calculate the factorials of a list of numbers that is given by the user. Note that after calculating the factorial it must be placed in the same index as the original number was.(Solve this problem by using a function to calculate the factorial)
"""

def calculate_factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

user_input = input("Enter a list of numbers separated by spaces: ")
user_numbers = [int(num) for num in user_input.split()]

for num in user_numbers:
    print(f"{calculate_factorial(num)}", end=" ")

user_input = input("Enter a list of numbers separated by spaces: ")
user_numbers = [int(num) for num in user_input.split()]

for num in user_numbers:
    print(f"{calculate_factorial(num)}", end=" ")

"""2.Take a certain number from the user and calculate the Fibonacci sequence up to that point and print the sequence as a list.
(Solve this problem by using a function to calculate the Fibonacci sequence)
"""

def fibonacci_sequence(n):
    if n == 0:
        return []
    elif n == 1:
        return [0]

    fib_sequence = [0, 1]

    i = 2
    while i < n:
        fib_sequence = fib_sequence + [fib_sequence[-1] + fib_sequence[-2]]
        i += 1

    return fib_sequence

user_input = int(input("Enter the number of Fibonacci numbers to calculate: "))

result = fibonacci_sequence(user_input)
print(f"{result}")

user_input = int(input("Enter the number of Fibonacci numbers to calculate: "))

result = fibonacci_sequence(user_input)
print(f"{result}")

"""3. Write a program that prompts the user to enter a series of grades, separated by spaces. The program should then calculate and display the average grade.
(Solve this problem by using a function to calculate the average)
"""

def calculate_average(grades):
    average = sum(grades) / len(grades)
    return average

user_input = input("Enter the grades, separated by spaces: ")
grades = [float(grade) for grade in user_input.split()]

average_grade = calculate_average(grades)

print(f"{average_grade}")

user_input = input("Enter the grades, separated by spaces: ")
grades = [float(grade) for grade in user_input.split()]

average_grade = calculate_average(grades)

print(f"{average_grade}")

"""4. Write a program that prompts the user to enter a string. The program should then count and display the occurrences of each vowel (a, e, i, o, u) in the string.
(Solve this problem by using a function to count the vowels)
"""

def count_vowels(input_string):
    vowels = "aeiou"
    vowel_counts = {}

    for vowel in vowels:
        count = input_string.lower().count(vowel)
        vowel_counts[vowel] = count

    return vowel_counts

user_input = input("Enter a string: ")

vowel_counts = count_vowels(user_input)

print(f"{vowel_counts}")

user_input = input("Enter a string: ")

vowel_counts = count_vowels(user_input)

print(f"{vowel_counts}")

"""5. Write a program that prompts the user to enter a list of elements separated by spaces. The program should then remove any duplicates from the list and display the resulting list.
(Solve this problem by using a function to remove duplicates)
"""

def remove_duplicates(input_list):
    unique_elements = []

    for element in input_list:
        if element not in unique_elements:
            unique_elements.append(element)

    return unique_elements

user_input = input("Enter a list of elements separated by spaces: ")

input_list = user_input.split()

result_list = remove_duplicates(input_list)

print(f"{result_list}")

user_input = input("Enter a list of elements separated by spaces: ")

input_list = user_input.split()

result_list = remove_duplicates(input_list)

print(f"{result_list}")